[SHUI YAO] Implement features for showing complete/uncompleted/overdue tasks
AY1920S1-CS2103T-F11-4/main pull request #83
Opened 2019-10-28 06:40 UTC by shuiyao-sg

Implement display features for complete/uncompleted/overdue tasks respectively. Corresponding User Guide sections are updated as well.

2019-10-28 07:28 UTC, Parcly-Taxel requested changes
Notwithstanding the review comments, this is good to merge.

2019-10-28 07:28 UTC, Parcly-Taxel commented on src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java
> +        //model.updateFilteredTaskList(Model.PREDICATE_SHOW_ALL_TASKS);
Since these lines are commented out, why not just remove them?

2019-10-28 07:28 UTC, Parcly-Taxel commented on src/main/java/seedu/address/logic/commands/task/DoneTaskCommand.java
> +        //model.updateFilteredTaskList(Model.PREDICATE_SHOW_ALL_TASKS);
Same here.

2019-10-28 07:28 UTC, Parcly-Taxel commented on src/main/java/seedu/address/model/Model.java
> +            }
These five lines can be replaced with `return taskDateTime.compareTo(now) < 0;`.

2019-10-28 14:05 UTC, Parcly-Taxel commented on src/main/java/seedu/address/model/Model.java
> +            }
OK, you can now remove these lines.

2019-10-28 14:05 UTC, shuiyao-sg commented
> Notwithstanding the review comments, this is good to merge.

Changes made. Can be safely merged. Thank you for your advice!

2019-10-29 00:40 UTC, Parcly-Taxel approved these changes

2019-10-29 00:55 UTC, merged